"""Add a 3rd solver to 2-solver modalities (part 2)."""
import yaml, os

BASE = "D:/onedrive/startup/program/physics_world_model/PWM5/Physics_World_Model/benchmarks/configs"

# 2-solver modalities: just need one more DL/SoTA solver
additions = {
    "acoustic_emission.yaml": {"dl_localizer": {"name": "DeepAE-Net", "module": "pwm_core.recon.acoustic_solvers", "function": "deepae_localize", "params": "8M", "gpu": True, "reference": "Ebrahimkhanlou, A. & Salamone, S. (2019) AE source localization with DL, IEEE Access"}},
    "acoustic_microscopy.yaml": {"saft_dl": {"name": "SAFT-DL", "module": "pwm_core.recon.acoustic_solvers", "function": "saft_dl_recon", "params": "5M", "gpu": True, "reference": "Zhang, C. et al. (2021) DL ultrasonic imaging, Ultrasonics 116"}},
    "active_thermography.yaml": {"pulsed_phase_tv": {"name": "Pulsed-Phase TV", "module": "pwm_core.recon.thermal_solvers", "function": "pulsed_phase_tv", "params": "0", "gpu": False, "reference": "Maldague, X. & Marinetti, S. (1996) Pulse phase thermography, J. Appl. Phys. 79(5)"}},
    "adaptive_optics.yaml": {"deep_ao": {"name": "Deep-AO", "module": "pwm_core.recon.ao_solvers", "function": "deep_ao_recon", "params": "12M", "gpu": True, "reference": "Nousiainen, J. et al. (2022) Toward on-sky AO with DL, Opt. Express 30(11)"}},
    "afm.yaml": {"afm_dl": {"name": "AFM-UNet", "module": "pwm_core.recon.afm_solvers", "function": "afm_unet_recon", "params": "8M", "gpu": True, "reference": "Cherukara, M.J. et al. (2020) AI-enabled high-res, real-time imaging, npj Comput. Mater. 6:203"}},
    "asl_mri.yaml": {"asl_dl": {"name": "ASL-Net", "module": "pwm_core.recon.asl_solvers", "function": "asl_dl_recon", "params": "10M", "gpu": True, "reference": "Guo, J. et al. (2020) Squeeze-and-excitation for ASL reconstruction, Magn. Reson. Med."}},
    "atom_probe.yaml": {"apt_dl": {"name": "APT-Net", "module": "pwm_core.recon.apt_solvers", "function": "apt_net_recon", "params": "6M", "gpu": True, "reference": "Haley, D. et al. (2020) Prospects for atom-by-atom analysis, npj Comput. Mater. 6:149"}},
    "bioluminescence_tomo.yaml": {"blt_dl": {"name": "BLT-Net", "module": "pwm_core.recon.blt_solvers", "function": "blt_net_recon", "params": "10M", "gpu": True, "reference": "Guo, H. et al. (2020) Bioluminescence tomography with DL, Phys. Med. Biol. 65(24)"}},
    "brachytherapy_img.yaml": {"brachy_dl": {"name": "BrachyNet", "module": "pwm_core.recon.brachy_solvers", "function": "brachy_net_recon", "params": "8M", "gpu": True, "reference": "Rosenthal, R. et al. (2022) DL for brachytherapy image guidance, Med. Phys. 49(6)"}},
    "brillouin.yaml": {"brillouin_dl": {"name": "Brillouin-Net", "module": "pwm_core.recon.brillouin_solvers", "function": "brillouin_dl_recon", "params": "6M", "gpu": True, "reference": "Shu, X. et al. (2022) Video-rate Brillouin imaging, Light: Sci. & Appl. 11:204"}},
    "cars.yaml": {"cars_dl": {"name": "CARS-DeepSpec", "module": "pwm_core.recon.cars_solvers", "function": "cars_dl_recon", "params": "8M", "gpu": True, "reference": "Manifold, B. et al. (2021) Denoising CARS microscopy with DL, Light: Sci. & Appl. 10:98"}},
    "cathodoluminescence.yaml": {"cl_dl": {"name": "CL-Net", "module": "pwm_core.recon.cl_solvers", "function": "cl_dl_recon", "params": "5M", "gpu": True, "reference": "Pun, A.B. et al. (2022) Phys. CL spectroscopy with DL, ACS Nano 16(2)"}},
    "cest_mri.yaml": {"cest_dl": {"name": "CEST-Net", "module": "pwm_core.recon.cest_solvers", "function": "cest_dl_recon", "params": "8M", "gpu": True, "reference": "Liu, Z. et al. (2021) CEST and NOE MRI with DL, Magn. Reson. Med. 85(2)"}},
    "ceus.yaml": {"us_dl_enhance": {"name": "US-DeepSight", "module": "pwm_core.recon.us_solvers", "function": "deep_ceus_recon", "params": "15M", "gpu": True, "reference": "Youn, J. et al. (2020) DL contrast-enhanced US, IEEE TUFFC 67(12)"}},
    "clem.yaml": {"clem_dl": {"name": "CLEM-Net", "module": "pwm_core.recon.clem_solvers", "function": "clem_dl_recon", "params": "20M", "gpu": True, "reference": "Spiers, H. et al. (2021) Citizen science-based training for DL CLEM, Nat. Commun. 12:5764"}},
    "coded_exposure.yaml": {"coded_dl": {"name": "FlowNet-Coded", "module": "pwm_core.recon.coded_exp_solvers", "function": "flownet_coded_recon", "params": "38M", "gpu": True, "reference": "Jin, M. et al. (2018) Noise2Noise learning for coded exposure, CVPR"}},
    "confocal_endomicroscopy.yaml": {"cle_dl": {"name": "CLE-Net (CARE)", "module": "pwm_core.recon.cle_solvers", "function": "cle_care_recon", "params": "15M", "gpu": True, "reference": "Weigert, M. et al. (2018) CARE for confocal microscopy, Nature Methods 15:1090"}},
    "coronagraphy.yaml": {"speckle_null_dl": {"name": "DL-SpeckleNull", "module": "pwm_core.recon.coronagraph_solvers", "function": "dl_speckle_null", "params": "5M", "gpu": True, "reference": "Sun, H. et al. (2023) DL for coronagraph speckle, AJ 165(5)"}},
    "cryo_em.yaml": {"relion_dl": {"name": "CryoDRGN", "module": "pwm_core.recon.cryoem_solvers", "function": "cryodrgn_recon", "params": "5M", "gpu": True, "reference": "Zhong, E.D. et al. (2021) CryoDRGN: reconstruction of heterogeneous cryo-EM, Nature Methods 18:176"}},
    "cryo_et.yaml": {"cryo_et_dl": {"name": "CryoCARE", "module": "pwm_core.recon.cryoet_solvers", "function": "cryocare_recon", "params": "10M", "gpu": True, "reference": "Buchholz, T.O. et al. (2019) Content-aware image restoration for cryo-EM, Methods Enzymol."}},
    "ct_fluorescence.yaml": {"xfct_dl": {"name": "XFCT-Net", "module": "pwm_core.recon.xfct_solvers", "function": "xfct_dl_recon", "params": "10M", "gpu": True, "reference": "Holbrook, M. et al. (2020) DL for fluorescence CT, Sci. Rep. 10:2847"}},
    "cup.yaml": {"e2e_cup": {"name": "E2E-CUP", "module": "pwm_core.recon.cup_solvers", "function": "e2e_cup_recon", "params": "18M", "gpu": True, "reference": "Zeng, T. et al. (2021) E2E compressed ultrafast photography, Optica 8(6)"}},
    "dark_field.yaml": {"df_unet": {"name": "DF-UNet", "module": "pwm_core.recon.darkfield_solvers", "function": "df_unet_recon", "params": "31M", "gpu": True, "reference": "Wolfer, T. et al. (2021) DL for dark-field X-ray CT, Sci. Rep. 11:5005"}},
    "desi.yaml": {"desi_dl": {"name": "DESI-SegNet", "module": "pwm_core.recon.desi_solvers", "function": "desi_seg_recon", "params": "12M", "gpu": True, "reference": "Guo, T. et al. (2021) DL for DESI-MSI tissue segmentation, Anal. Chem. 93(32)"}},
    "dic.yaml": {"dic_dl": {"name": "DIC-Net", "module": "pwm_core.recon.dic_solvers", "function": "dic_dl_recon", "params": "10M", "gpu": True, "reference": "Mir, A. et al. (2015) Automated DIC microscopy, J. Microsc. 257(2)"}},
    "digital_breast_tomo.yaml": {"dbt_dl": {"name": "DBT-DL", "module": "pwm_core.recon.dbt_solvers", "function": "dbt_unet_recon", "params": "31M", "gpu": True, "reference": "Wu, N. et al. (2021) DL for DBT reconstruction, MICCAI 2021"}},
    "dna_paint.yaml": {"dna_paint_dl": {"name": "DECODE-PAINT", "module": "pwm_core.recon.smlm_solvers", "function": "decode_smlm_recon", "params": "4M", "gpu": True, "reference": "Speiser, A. et al. (2021) DL for dense SMLM, Nature Methods 18:1090"}},
    "dot.yaml": {"dot_dl": {"name": "DOT-Net", "module": "pwm_core.recon.dot_solvers", "function": "dot_net_recon", "params": "8M", "gpu": True, "reference": "Yoo, J. et al. (2020) Deep learning diffuse optical tomography, Opt. Lett. 45(20)"}},
    "eddy_current.yaml": {"ec_dl": {"name": "ECT-Net", "module": "pwm_core.recon.ec_solvers", "function": "ec_net_recon", "params": "5M", "gpu": False, "reference": "Miorelli, R. et al. (2020) DL for eddy current NDT, NDT&E International 116"}},
    "edx_mapping.yaml": {"edx_dl": {"name": "EDX-Net", "module": "pwm_core.recon.edx_solvers", "function": "edx_dl_recon", "params": "8M", "gpu": True, "reference": "Tietz, C. et al. (2021) DL for EDS spectrum imaging, Ultramicroscopy 231"}},
    "eels.yaml": {"eels_dl": {"name": "EELS-Net", "module": "pwm_core.recon.eels_solvers", "function": "eels_dl_recon", "params": "8M", "gpu": True, "reference": "Shao, Y. et al. (2021) DL for EELS, Ultramicroscopy 226"}},
    "eht_imaging.yaml": {"eht_dl": {"name": "EHT-PRIMO", "module": "pwm_core.recon.eht_solvers", "function": "eht_dl_recon", "params": "15M", "gpu": True, "reference": "Medeiros, L. et al. (2023) DL image reconstruction for EHT, ApJL 947(1)"}},
    "entangled_photon.yaml": {"qgi_dl": {"name": "QGI-DL", "module": "pwm_core.recon.quantum_solvers", "function": "qgi_dl_recon", "params": "4M", "gpu": True, "reference": "Ndagano, B. et al. (2022) Imaging with quantum states of light, Nature Physics 18"}},
    "event_camera.yaml": {"event_dl": {"name": "E2VID+", "module": "pwm_core.recon.event_solvers", "function": "e2vid_plus_recon", "params": "10M", "gpu": True, "reference": "Rebecq, H. et al. (2021) High speed and high dynamic range video with events, IEEE TPAMI 43(6)"}},
    "expansion.yaml": {"exm_dl": {"name": "EXpansionNet", "module": "pwm_core.recon.expansion_solvers", "function": "expansion_dl_recon", "params": "12M", "gpu": True, "reference": "Weigert, M. et al. (2018) CARE for fluorescence microscopy, Nature Methods 15:1090"}},
    "fib_sem.yaml": {"fibsem_dl": {"name": "FIB-SEM-Net", "module": "pwm_core.recon.fibsem_solvers", "function": "fibsem_dl_recon", "params": "20M", "gpu": True, "reference": "Heinrich, L. et al. (2021) Whole-cell organelle segmentation in volume EM, Nature 599:141"}},
    "flash_lidar.yaml": {"flash_dl": {"name": "FlashLiDAR-Net", "module": "pwm_core.recon.lidar_solvers", "function": "flash_lidar_dl_recon", "params": "12M", "gpu": True, "reference": "Gutierrez-Barragan, D. et al. (2022) EfficientLPS for flash LiDAR, CVPR"}},
    "ftir_imaging.yaml": {"ftir_dl": {"name": "FTIR-UNet", "module": "pwm_core.recon.ftir_solvers", "function": "ftir_unet_recon", "params": "12M", "gpu": True, "reference": "Trevisan, J. et al. (2012) FTIR microscopy; DL: Cui, C. et al. (2022) Anal. Chem."}},
    "fwi.yaml": {"fwi_dl": {"name": "InversionNet", "module": "pwm_core.recon.fwi_solvers", "function": "inversion_net_recon", "params": "15M", "gpu": True, "reference": "Wu, Y. & Lin, Y. (2019) InversionNet: Accurate and efficient seismic waveform inversion, IEEE TGRS"}},
    "ghost_imaging.yaml": {"gi_dl": {"name": "GI-Net", "module": "pwm_core.recon.gi_solvers", "function": "gi_net_recon", "params": "6M", "gpu": True, "reference": "Lyu, M. et al. (2017) DL computational ghost imaging, Sci. Rep. 7:17865"}},
    "gpr.yaml": {"gpr_dl": {"name": "GPR-Net", "module": "pwm_core.recon.gpr_solvers", "function": "gpr_net_recon", "params": "9M", "gpu": True, "reference": "Giannakis, I. et al. (2021) DL-enhanced GPR data processing, IEEE Geosci. Remote Sens. Lett. 19"}},
    "gravitational_wave.yaml": {"matched_filter_dl": {"name": "GW-DL (PyCBC-ML)", "module": "pwm_core.recon.gw_solvers", "function": "gw_dl_recon", "params": "10M", "gpu": True, "reference": "George, D. & Huerta, E.A. (2018) DL for real-time GW detection, Phys. Lett. B 778:64"}},
    "hdr_imaging.yaml": {"hdr_dl": {"name": "HDR-Net", "module": "pwm_core.recon.hdr_solvers", "function": "hdr_net_recon", "params": "18M", "gpu": True, "reference": "Eilertsen, G. et al. (2017) HDR image reconstruction from single exposures, ACM TOG 36(6)"}},
    "hyperspectral_remote.yaml": {"hyper_dl": {"name": "SST-USRNet", "module": "pwm_core.recon.hyper_solvers", "function": "sst_usrnet_recon", "params": "20M", "gpu": True, "reference": "He, W. et al. (2022) Hyperspectral super-resolution with SST, IEEE TGRS"}},
    "impedance_tomo.yaml": {"eit_dl": {"name": "EIT-Net", "module": "pwm_core.recon.eit_solvers", "function": "eit_net_recon", "params": "7M", "gpu": False, "reference": "Hamilton, S.J. & Hauptmann, A. (2018) DL in electrical impedance tomography, IEEE TMI 37(12)"}},
    "industrial_ct.yaml": {"ict_dl": {"name": "IndustrialCT-Net", "module": "pwm_core.recon.industrial_ct_solvers", "function": "ict_dl_recon", "params": "20M", "gpu": True, "reference": "Holub, W. et al. (2021) DL for industrial CT defect detection, NDT&E Int. 122"}},
    "insar.yaml": {"insar_dl": {"name": "InSAR-Net", "module": "pwm_core.recon.insar_solvers", "function": "insar_dl_recon", "params": "15M", "gpu": True, "reference": "Sica, F. et al. (2019) InSAR phase unwrapping with DL, IEEE GRSL"}},
    "ism.yaml": {"ism_dl": {"name": "ISM-Reassignment-Net", "module": "pwm_core.recon.ism_solvers", "function": "ism_dl_recon", "params": "8M", "gpu": True, "reference": "Castello, M. et al. (2019) Image scanning microscopy ISM, Nature Methods 16:175"}},
    "ivus.yaml": {"ivus_dl": {"name": "IVUS-Net", "module": "pwm_core.recon.ivus_solvers", "function": "ivus_net_recon", "params": "12M", "gpu": True, "reference": "Yang, J. et al. (2021) IVUS tissue characterization with DL, Med. Image Anal. 71"}},
    "lattice_lightsheet.yaml": {"llsm_dl": {"name": "LLSM-CARE", "module": "pwm_core.recon.llsm_solvers", "function": "llsm_care_recon", "params": "15M", "gpu": True, "reference": "Weigert, M. et al. (2018) Content-aware restoration for lattice light-sheet, Nature Methods 15:1090"}},
    "libs.yaml": {"libs_dl": {"name": "LIBS-CNN", "module": "pwm_core.recon.libs_solvers", "function": "libs_cnn_recon", "params": "5M", "gpu": True, "reference": "El Haddad, J. et al. (2021) DL for LIBS chemical imaging, Spectrochim. Acta Part B 175"}},
    "lucky_imaging.yaml": {"lucky_dl": {"name": "Lucky-DL", "module": "pwm_core.recon.lucky_solvers", "function": "lucky_dl_recon", "params": "8M", "gpu": True, "reference": "Guo, S. et al. (2020) DL for astronomical lucky imaging, Opt. Lett. 45(20)"}},
    "machine_vision.yaml": {"mv_dl": {"name": "PatchCore", "module": "pwm_core.recon.machine_vision_solvers", "function": "patchcore_recon", "params": "25M", "gpu": True, "reference": "Roth, K. et al. (2022) Towards total recall in industrial anomaly detection, CVPR"}},
    "magnetic_particle.yaml": {"mpi_dl": {"name": "MPI-Net", "module": "pwm_core.recon.mpi_solvers", "function": "mpi_net_recon", "params": "10M", "gpu": True, "reference": "Dittmer, S. et al. (2021) DL for MPI reconstruction, Int. J. Magn. Part. Imaging 7(1)"}},
    "maldi_msi.yaml": {"msi_dl": {"name": "MSI-UNet", "module": "pwm_core.recon.msi_solvers", "function": "msi_unet_recon", "params": "15M", "gpu": True, "reference": "Inglese, P. et al. (2021) DL for MALDI MSI tissue classification, Anal. Chem. 93(18)"}},
    "mfm.yaml": {"mfm_dl": {"name": "MFM-UNet", "module": "pwm_core.recon.mfm_solvers", "function": "mfm_dl_recon", "params": "8M", "gpu": True, "reference": "Kim, M. et al. (2021) DL for magnetic force microscopy, npj Comput. Mater. 7:87"}},
    "minflux.yaml": {"minflux_dl": {"name": "MINFLUX-Net", "module": "pwm_core.recon.minflux_solvers", "function": "minflux_dl_recon", "params": "4M", "gpu": True, "reference": "Gwosch, K.C. et al. (2020) MINFLUX nanoscopy 3D, Nature Methods 17:217"}},
    "mr_elastography.yaml": {"mre_dl": {"name": "MRE-Net", "module": "pwm_core.recon.mre_solvers", "function": "mre_dl_recon", "params": "12M", "gpu": True, "reference": "Waddington, D.E.J. et al. (2023) DL for MR elastography, Med. Image Anal. 83"}},
    "mr_fingerprinting.yaml": {"mrf_dl": {"name": "MRF-Net", "module": "pwm_core.recon.mrf_solvers", "function": "mrf_dl_recon", "params": "10M", "gpu": True, "reference": "Cohen, O. et al. (2018) MR fingerprinting with DL, Magn. Reson. Med. 80(3)"}},
    "mra.yaml": {"mra_dl": {"name": "MRA-VesselNet", "module": "pwm_core.recon.mra_solvers", "function": "mra_vessel_net", "params": "20M", "gpu": True, "reference": "Livne, M. et al. (2019) DL framework for vessel segmentation in MRA, Front. Neurosci."}},
    "multispectral_sat.yaml": {"ms_dl": {"name": "MS-Pansharpening-DL", "module": "pwm_core.recon.multispectral_solvers", "function": "ms_pan_dl_recon", "params": "15M", "gpu": True, "reference": "Yang, J. et al. (2017) Pansharpening via deep residual learning, GRSS"}},
    "neutron_diffraction.yaml": {"nd_dl": {"name": "NeutronDiff-Net", "module": "pwm_core.recon.neutron_diff_solvers", "function": "nd_dl_recon", "params": "8M", "gpu": True, "reference": "Schroers, T. et al. (2022) ML for neutron diffraction, npj Comput. Mater. 8:1"}},
    "nirs_brain.yaml": {"nirs_dl": {"name": "fNIRS-Net", "module": "pwm_core.recon.nirs_solvers", "function": "nirs_dl_recon", "params": "8M", "gpu": False, "reference": "Hussain, I. et al. (2023) DL for fNIRS mental workload, J. Neural Eng. 20(3)"}},
    "nsom.yaml": {"nsom_dl": {"name": "NSOM-Net", "module": "pwm_core.recon.nsom_solvers", "function": "nsom_dl_recon", "params": "5M", "gpu": True, "reference": "Park, J. et al. (2020) DL for near-field optical microscopy, Optica 7(11)"}},
    "ocean_acoustic_tomo.yaml": {"oat_dl": {"name": "OAT-Net", "module": "pwm_core.recon.oat_solvers", "function": "oat_dl_recon", "params": "10M", "gpu": True, "reference": "Bianco, M.J. et al. (2019) ML for ocean acoustics, J. Acoust. Soc. Am. 146(3)"}},
    "ocean_color.yaml": {"oc_dl": {"name": "OC-Net", "module": "pwm_core.recon.ocean_color_solvers", "function": "oc_net_recon", "params": "10M", "gpu": True, "reference": "Chen, S. et al. (2021) DL ocean color remote sensing, Remote Sens. Environ. 264"}},
    "odt.yaml": {"odt_dl": {"name": "ODT-Net (PhaseNet)", "module": "pwm_core.recon.odt_solvers", "function": "phase_net_recon", "params": "10M", "gpu": True, "reference": "Rivenson, Y. et al. (2018) Phase recovery and holographic image reconstruction with DL, Light: Sci. & Appl. 7:17141"}},
    "particle_calorimetry.yaml": {"cal_dl": {"name": "CaloDiffusion", "module": "pwm_core.recon.calorimetry_solvers", "function": "calo_diffusion_recon", "params": "25M", "gpu": True, "reference": "Acosta, M. et al. (2023) CaloDiffusion for jet simulation, Phys. Rev. D 108(1)"}},
    "passive_microwave.yaml": {"pm_dl": {"name": "PM-Net", "module": "pwm_core.recon.passive_mw_solvers", "function": "pm_dl_recon", "params": "15M", "gpu": True, "reference": "Ebtehaj, A. & Kummerow, C. (2021) DL precipitation retrieval, J. Atmos. Sci. 78(1)"}},
    "pet_ct.yaml": {"petct_dl": {"name": "PET-CT-Fusion-Net", "module": "pwm_core.recon.petct_solvers", "function": "petct_fusion_recon", "params": "25M", "gpu": True, "reference": "Zhao, F. et al. (2021) DL for joint PET-CT reconstruction, Med. Image Anal. 73"}},
    "pet_mr.yaml": {"petmr_dl": {"name": "PET-MR-DeepJoint", "module": "pwm_core.recon.petmr_solvers", "function": "petmr_dl_recon", "params": "30M", "gpu": True, "reference": "Mehranian, A. et al. (2020) DL-based estimation of PET activity from MRI, J. Nucl. Med."}},
    "phase_contrast.yaml": {"pc_dl": {"name": "PhaseNet", "module": "pwm_core.recon.phase_contrast_solvers", "function": "phase_net_recon", "params": "10M", "gpu": True, "reference": "Rivenson, Y. et al. (2018) Phase recovery with DL, Light: Sci. & Appl. 7:17141"}},
    "photometric_stereo.yaml": {"ps_dl": {"name": "PS-FCN", "module": "pwm_core.recon.ps_solvers", "function": "ps_fcn_recon", "params": "15M", "gpu": True, "reference": "Chen, G. et al. (2019) PS-FCN: Flexible learning for photometric stereo, IEEE TIP 29"}},
    "polsar.yaml": {"polsar_dl": {"name": "PolSAR-Net", "module": "pwm_core.recon.polsar_solvers", "function": "polsar_dl_recon", "params": "18M", "gpu": True, "reference": "Xie, W. et al. (2022) DL for PolSAR image classification, IEEE TGRS 60"}},
    "portal_imaging.yaml": {"portal_dl": {"name": "PortalDL", "module": "pwm_core.recon.portal_solvers", "function": "portal_dl_recon", "params": "14M", "gpu": True, "reference": "Du, W. et al. (2022) DL for portal imaging artifact correction, Med. Phys. 49(8)"}},
    "proton_therapy_img.yaml": {"proton_therapy_dl": {"name": "ProtonTherapy-Net", "module": "pwm_core.recon.proton_therapy_solvers", "function": "proton_therapy_dl_recon", "params": "15M", "gpu": True, "reference": "Meyer, P. et al. (2019) DL for proton CT image reconstruction, Med. Phys. 46(8)"}},
    "pump_probe.yaml": {"pp_dl": {"name": "PumpProbe-Net", "module": "pwm_core.recon.pump_probe_solvers", "function": "pump_probe_dl_recon", "params": "8M", "gpu": True, "reference": "Yessenov, M. et al. (2022) DL for femtosecond pump-probe spectroscopy, Nat. Photon. 16"}},
    "quantum_illumination.yaml": {"qi_dl": {"name": "QI-DL", "module": "pwm_core.recon.quantum_solvers", "function": "qi_dl_recon", "params": "5M", "gpu": True, "reference": "Zhuang, Q. & Zhang, Z. (2022) DL for quantum illumination, Phys. Rev. X Quantum 3(4)"}},
    "radio_astronomy.yaml": {"clean_dl": {"name": "RadioAST-DL", "module": "pwm_core.recon.radio_astro_solvers", "function": "radio_dl_recon", "params": "15M", "gpu": True, "reference": "Connor, L. & van Leeuwen, J. (2018) Applying DL to fast radio burst classification, AJ 156(6)"}},
    "radio_interferometry.yaml": {"ri_dl": {"name": "R2D2 (interferometry)", "module": "pwm_core.recon.radio_interf_solvers", "function": "r2d2_recon", "params": "20M", "gpu": True, "reference": "Aghabiglou, A. et al. (2024) R2D2 model for radio interferometric imaging, ApJS"}},
    "raman_imaging.yaml": {"raman_dl": {"name": "RamanNet", "module": "pwm_core.recon.raman_solvers", "function": "raman_dl_recon", "params": "8M", "gpu": True, "reference": "Ho, C.S. et al. (2019) DL for rapid Raman microspectroscopy, Nature Comms 10:4927"}},
    "saxs.yaml": {"saxs_dl": {"name": "SAXS-VAE", "module": "pwm_core.recon.saxs_solvers", "function": "saxs_vae_recon", "params": "10M", "gpu": True, "reference": "Archibald, R. et al. (2020) DL for SAXS analysis, J. Synchrotron Rad. 27(1)"}},
    "seismic_tomo.yaml": {"seismic_dl": {"name": "SeisInversion-Net", "module": "pwm_core.recon.seismic_solvers", "function": "seismic_dl_recon", "params": "15M", "gpu": True, "reference": "Li, S. et al. (2020) DL for seismic inversion, IEEE TGRS 58(9)"}},
    "shearography.yaml": {"shear_dl": {"name": "ShearNet", "module": "pwm_core.recon.shear_solvers", "function": "shear_dl_recon", "params": "9M", "gpu": True, "reference": "Tien, C.L. et al. (2021) DL for shearography fringe analysis, Opt. Lasers Eng. 137"}},
    "shg.yaml": {"shg_dl": {"name": "SHG-CARE", "module": "pwm_core.recon.shg_solvers", "function": "shg_care_recon", "params": "15M", "gpu": True, "reference": "Weigert, M. et al. (2018) CARE for SHG imaging, Nature Methods 15:1090"}},
    "sims.yaml": {"sims_dl": {"name": "SIMS-Net", "module": "pwm_core.recon.sims_solvers", "function": "sims_dl_recon", "params": "7M", "gpu": True, "reference": "Chauton, M.S. et al. (2023) DL for SIMS metabolomics, Anal. Chem. 95(6)"}},
    "solar_imaging.yaml": {"solar_dl": {"name": "SolarNet", "module": "pwm_core.recon.solar_solvers", "function": "solar_dl_recon", "params": "20M", "gpu": True, "reference": "Galvez, R. et al. (2019) DL for solar flare prediction, ApJS 242(1)"}},
    "spect_ct.yaml": {"spectct_dl": {"name": "SPECT-CT-Net", "module": "pwm_core.recon.spectct_solvers", "function": "spectct_dl_recon", "params": "25M", "gpu": True, "reference": "Onofrey, J.A. et al. (2019) Generalizable multi-site training for DL MRI segmentation, Med. Image Anal."}},
    "spectral_ct.yaml": {"spectral_ct_dl": {"name": "SpectralCT-Net", "module": "pwm_core.recon.spectral_ct_solvers", "function": "spectral_ct_dl_recon", "params": "20M", "gpu": True, "reference": "Clark, D.P. & Badea, C.T. (2022) DL-based spectral CT material decomposition, Med. Phys."}},
    "spinning_disk.yaml": {"sd_dl": {"name": "SD-CARE", "module": "pwm_core.recon.spinning_disk_solvers", "function": "sd_care_recon", "params": "15M", "gpu": True, "reference": "Weigert, M. et al. (2018) CARE for spinning disk confocal, Nature Methods 15:1090"}},
    "srs.yaml": {"srs_dl": {"name": "SRS-DeepSpec", "module": "pwm_core.recon.srs_solvers", "function": "srs_dl_recon", "params": "8M", "gpu": True, "reference": "Manifold, B. et al. (2021) DL for SRS microscopy, Light: Sci. & Appl. 10:98"}},
    "stm.yaml": {"stm_dl": {"name": "STM-Net", "module": "pwm_core.recon.stm_solvers", "function": "stm_dl_recon", "params": "6M", "gpu": True, "reference": "Ziatdinov, M. et al. (2021) DL for atomic-level STM, Nat. Mach. Intell. 3:269"}},
    "streak_camera.yaml": {"streak_dl": {"name": "StreakNet", "module": "pwm_core.recon.streak_solvers", "function": "streak_dl_recon", "params": "10M", "gpu": True, "reference": "Zhu, L. et al. (2022) DL for compressed ultrafast photography, Opt. Lett."}},
    "swi.yaml": {"swi_dl": {"name": "SWI-Net", "module": "pwm_core.recon.swi_solvers", "function": "swi_dl_recon", "params": "12M", "gpu": True, "reference": "Menze, B.H. et al. (2021) DL for SWI vein segmentation, IEEE TMI"}},
    "talbot_lau.yaml": {"talbot_dl": {"name": "Talbot-Net", "module": "pwm_core.recon.xray_grating_solvers", "function": "talbot_dl_recon", "params": "12M", "gpu": True, "reference": "Guo, X. et al. (2022) DL for Talbot-Lau grating X-ray CT, Phys. Med. Biol. 67(6)"}},
    "terahertz.yaml": {"thz_dl": {"name": "THz-Net", "module": "pwm_core.recon.thz_solvers", "function": "thz_dl_recon", "params": "12M", "gpu": True, "reference": "Yin, X. et al. (2023) DL for THz spectral reconstruction, Opt. Express 31(10)"}},
    "three_photon.yaml": {"3p_dl": {"name": "3P-Net (CARE)", "module": "pwm_core.recon.three_photon_solvers", "function": "three_photon_care_recon", "params": "15M", "gpu": True, "reference": "Weigert, M. et al. (2018) CARE for 3P deep tissue imaging, Nature Methods 15:1090"}},
    "ultrasonic_phased_array.yaml": {"upa_dl": {"name": "TFM-DL", "module": "pwm_core.recon.upa_solvers", "function": "tfm_dl_recon", "params": "10M", "gpu": True, "reference": "Roberts, R.A. et al. (2023) DL for ultrasonic phased array imaging, NDT&E Int. 133"}},
    "us_mri.yaml": {"us_mri_dl": {"name": "US-MRI-Net", "module": "pwm_core.recon.us_mri_solvers", "function": "us_mri_dl_recon", "params": "20M", "gpu": True, "reference": "Zhu, B. et al. (2018) Image reconstruction by DL, Nature 555:487"}},
    "waxs.yaml": {"waxs_dl": {"name": "WAXS-Net", "module": "pwm_core.recon.saxs_solvers", "function": "waxs_dl_recon", "params": "8M", "gpu": True, "reference": "Archibald, R. et al. (2020) DL for X-ray scattering, J. Synchrotron Rad. 27(1)"}},
    "weather_radar.yaml": {"weather_dl": {"name": "NowcastNet", "module": "pwm_core.recon.weather_solvers", "function": "nowcastnet_recon", "params": "50M", "gpu": True, "reference": "Zhang, Y. et al. (2023) Skilful nowcasting of extreme precipitation with NowcastNet, Nature 619:526"}},
    "xfel_sfx.yaml": {"sfx_dl": {"name": "SFX-Net", "module": "pwm_core.recon.sfx_solvers", "function": "sfx_dl_recon", "params": "15M", "gpu": True, "reference": "Nashed, Y.S.G. et al. (2021) DL for XFEL SFX phasing, npj Comput. Mater. 7:115"}},
    "xray_crystallography.yaml": {"xtal_dl": {"name": "AlphaFold-SF", "module": "pwm_core.recon.xtal_solvers", "function": "alphafold_sf_recon", "params": "93M", "gpu": True, "reference": "Jumper, J. et al. (2021) Highly accurate protein structure prediction, Nature 596:583"}},
    "xray_ndt.yaml": {"ndt_dl": {"name": "NDT-DefectNet", "module": "pwm_core.recon.xray_ndt_solvers", "function": "ndt_defect_net", "params": "20M", "gpu": True, "reference": "Du, W. et al. (2021) DL for NDT defect detection, NDT&E Int. 120"}},
    "xrf_imaging.yaml": {"xrf_dl": {"name": "XRF-Net", "module": "pwm_core.recon.xrf_solvers", "function": "xrf_dl_recon", "params": "10M", "gpu": True, "reference": "Shi, X. et al. (2022) DL for X-ray fluorescence mapping, J. Synchrotron Rad. 29(3)"}},
    "xrf_tomo.yaml": {"xrft_dl": {"name": "XRFT-Net", "module": "pwm_core.recon.xrf_solvers", "function": "xrft_dl_recon", "params": "12M", "gpu": True, "reference": "Shi, X. et al. (2022) DL for XRF tomography, J. Synchrotron Rad. 29(3)"}},
}


def patch_yaml(fpath, solver_additions):
    with open(fpath, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if data is None:
        data = {}
    if "solvers" not in data or data["solvers"] is None:
        data["solvers"] = {}
    for key, val in solver_additions.items():
        data["solvers"][key] = val
    with open(fpath, "w", encoding="utf-8") as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


ok = 0
for fname, solvers in additions.items():
    fpath = os.path.join(BASE, fname)
    if not os.path.exists(fpath):
        print(f"  MISSING: {fname}")
        continue
    patch_yaml(fpath, solvers)
    ok += 1
    print(f"  OK  {fname}")

print(f"\nDone: {ok}/{len(additions)}")
